package Program;

import Entities.Bot;
import Entities.JogoDaVelha;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Entities.JogoDaVelha;
import Network.Client;
import Network.Server;
import java.awt.Component;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author bruno
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public App() {
        initComponents();
        this.setVisible(false);
        Menu.setVisible(true);

    }

    private Server server;
    private Client client;
    private boolean host;
    private boolean online = false;

    private JButton[][] botoes;
    private JogoDaVelha Jogo;
    private Bot bot = new Bot();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Menu = new javax.swing.JFrame();
        btnClient = new javax.swing.JButton();
        btnJogarComBot = new javax.swing.JButton();
        btnMpLocal1 = new javax.swing.JButton();
        btnServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnJogador2 = new javax.swing.JButton();
        btnJogador1 = new javax.swing.JButton();
        btnNome1 = new javax.swing.JTextField();
        btnNome2 = new javax.swing.JTextField();
        btnVitoriasJ1 = new javax.swing.JButton();
        btnDerrotasJ1 = new javax.swing.JButton();
        btnVitoriasJ2 = new javax.swing.JButton();
        btnDerrotasJ2 = new javax.swing.JButton();
        btnEmpates = new javax.swing.JButton();

        Menu.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Menu.setMinimumSize(new java.awt.Dimension(383, 318));
        Menu.setResizable(false);
        Menu.setSize(new java.awt.Dimension(383, 318));
        Menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClient.setText("Conectar");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 250, -1));

        btnJogarComBot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnJogarComBot.setText("Jogar com bot");
        btnJogarComBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarComBotActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnJogarComBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 250, -1));

        btnMpLocal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMpLocal1.setText("Jogar com amigo");
        btnMpLocal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMpLocal1ActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnMpLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, -1));

        btnServer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnServer.setText("Abrir conexão");
        btnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(btnServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bruno\\Documents\\Orientação a objetos e UML\\JogoDaVelha\\src\\main\\java\\Images\\background.jpg")); // NOI18N
        Menu.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn2.setBackground(new java.awt.Color(255, 153, 102));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 153, 102));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 153, 102));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 153, 102));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 153, 102));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 153, 102));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 153, 102));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 153, 102));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 153, 102));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnReset.setBackground(new java.awt.Color(255, 153, 102));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setText("RESETAR");
        btnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnJogador2.setBackground(new java.awt.Color(255, 153, 102));
        btnJogador2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJogador2.setBorder(null);
        btnJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogador2ActionPerformed(evt);
            }
        });

        btnJogador1.setBackground(new java.awt.Color(255, 153, 102));
        btnJogador1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJogador1.setBorder(null);
        btnJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogador1ActionPerformed(evt);
            }
        });

        btnNome1.setEditable(false);
        btnNome1.setBackground(new java.awt.Color(255, 153, 102));
        btnNome1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnNome1.setText("Jogando como X");
        btnNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNome1ActionPerformed(evt);
            }
        });

        btnNome2.setEditable(false);
        btnNome2.setBackground(new java.awt.Color(255, 153, 102));
        btnNome2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnNome2.setText("Jogando como O");

        btnVitoriasJ1.setBackground(new java.awt.Color(102, 255, 102));
        btnVitoriasJ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVitoriasJ1.setBorder(null);
        btnVitoriasJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoriasJ1ActionPerformed(evt);
            }
        });

        btnDerrotasJ1.setBackground(new java.awt.Color(255, 51, 51));
        btnDerrotasJ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDerrotasJ1.setBorder(null);
        btnDerrotasJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotasJ1ActionPerformed(evt);
            }
        });

        btnVitoriasJ2.setBackground(new java.awt.Color(102, 255, 102));
        btnVitoriasJ2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVitoriasJ2.setBorder(null);
        btnVitoriasJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoriasJ2ActionPerformed(evt);
            }
        });

        btnDerrotasJ2.setBackground(new java.awt.Color(255, 51, 51));
        btnDerrotasJ2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDerrotasJ2.setBorder(null);
        btnDerrotasJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotasJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnJogador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNome2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnNome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnJogador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVitoriasJ1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDerrotasJ1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVitoriasJ2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDerrotasJ2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVitoriasJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDerrotasJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVitoriasJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDerrotasJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEmpates.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed

        Jogo.jogada(0, 0);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(1);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(1);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);


    }//GEN-LAST:event_btn1ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        Jogo.jogada(2, 1);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(8);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(8);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Jogo.jogada(0, 1);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(2);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(2);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);


    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Jogo.jogada(0, 2);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(3);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(3);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        Jogo.jogada(1, 1);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(5);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(5);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Jogo.jogada(1, 0);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(4);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(4);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        Jogo.jogada(1, 2);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(6);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(6);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        Jogo.jogada(2, 0);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(7);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(7);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        Jogo.jogada(2, 2);
        bot.jogadaAleatoria(Jogo.getTabuleiro(), Jogo);

        if (online == true) {
            if (host == true) {
                try {

                    server.sendData(9);
                    server.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {

                    client.sendData(9);
                    client.lerJogada(Jogo.getTabuleiro());
                    Jogo.passarVez();
                    Jogo.probabilidades();

                } catch (IOException ex) {
                    Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        Jogo.checkBoard(botoes);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        Jogo.resetar(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnVitoriasJ1, btnVitoriasJ2, btnEmpates, btnDerrotasJ1, btnDerrotasJ2);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador1ActionPerformed

    }//GEN-LAST:event_btnJogador1ActionPerformed

    private void btnNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNome1ActionPerformed

    private void btnJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJogador2ActionPerformed

    private void btnVitoriasJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoriasJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVitoriasJ1ActionPerformed

    private void btnDerrotasJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotasJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerrotasJ1ActionPerformed

    private void btnVitoriasJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoriasJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVitoriasJ2ActionPerformed

    private void btnDerrotasJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotasJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerrotasJ2ActionPerformed

    private void btnJogarComBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarComBotActionPerformed

        Menu.dispose();
        this.setVisible(true);
        Jogo = new JogoDaVelha(btnJogador1);
        bot = new Bot();
        bot.setBot();
        botoes = new JButton[3][3];
        Jogo.atribuirBotoes(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, botoes);
        btnJogador2.setText(bot.getNome());

    }//GEN-LAST:event_btnJogarComBotActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed

        client = new Client();
        client.getServerPort();
        client.getServerIP();
        online = true;

        try {
            client.connect();
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        Menu.dispose();
        this.setVisible(true);
        Jogo = new JogoDaVelha(btnJogador1, btnJogador2, online);
        botoes = new JButton[3][3];
        Jogo.atribuirBotoes(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, botoes);
        Jogo.passarVez();

        try {
            client.lerJogada(Jogo.getTabuleiro());
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        btnReset.setEnabled(false);

        Jogo.checkBoard(botoes);


    }//GEN-LAST:event_btnClientActionPerformed

    private void btnMpLocal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMpLocal1ActionPerformed
        // TODO add your handling code here:
        Menu.dispose();
        this.setVisible(true);
        Jogo = new JogoDaVelha(btnJogador1, btnJogador2, online);
        botoes = new JButton[3][3];
        Jogo.atribuirBotoes(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, botoes);
    }//GEN-LAST:event_btnMpLocal1ActionPerformed

    private void btnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerActionPerformed

        server = new Server();
        server.getPort();
        online = true;
        host = true;
        try {
            // TODO add your handling code here:
            server.runServer();
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        Menu.dispose();
        this.setVisible(true);
        Jogo = new JogoDaVelha(btnJogador1, btnJogador2, online);
        botoes = new JButton[3][3];
        Jogo.atribuirBotoes(btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, botoes);
        btnReset.setEnabled(false);

    }//GEN-LAST:event_btnServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new App().setVisible(false);

                JButton[][] botoes = new JButton[3][3];

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Menu;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnDerrotasJ1;
    private javax.swing.JButton btnDerrotasJ2;
    private javax.swing.JButton btnEmpates;
    private javax.swing.JButton btnJogador1;
    private javax.swing.JButton btnJogador2;
    private javax.swing.JButton btnJogarComBot;
    private javax.swing.JButton btnMpLocal1;
    private javax.swing.JTextField btnNome1;
    private javax.swing.JTextField btnNome2;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnServer;
    private javax.swing.JButton btnVitoriasJ1;
    private javax.swing.JButton btnVitoriasJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
